GET http://localhost:5000

###

POST http://localhost:5000/print
content-type: application/json

{
    "density": 3,
    "quantity": 1,
    "image": "iVBORw0KGgoAAAANSUhEUgAAAXwAAABgAQAAAAA2//QzAAAACXBIWXMAAA7DAAAOwwHHb6hkAAAAGXRFWHRTb2Z0d2FyZQB3d3cuaW5rc2NhcGUub3Jnm+48GgAAATxJREFUWIXt1FFKAzEQANCJC8YPMf30y1ykNFfyAIXJzUzxIOYI+czHsuNkV6WVtZMgVZEMYQMhL7CTmQBcPBw1he+ggw46+JdgVNXAgwpgIzx++YSuAt8KoBWoVA3omQ406Qkzru9fB4boh8AT0QsR1oLxfqBbRenaikAvYAN0AxSuZDAsAAB5eBABqTcQECJCEEAA53EGOrmhDBnwmQWY7HTe6SyDqBcwWgb8FUFWM7CjNWMVmOAI2EkAh7KKH2BbBUIrSK4R5G8BKUufwK4FZFdzD1ytuPy0WUCWgY2c1rzn4mOg5eJ74C7ImPbKoxldRXkz4NJIW54YiA1UQCm+tOeJgdii5anUM9gMBcS7s+Ao3tN5Pq2/AvLJDhm41AhMwDbA194KTlYrwNAIoq0F69FBBx108PfAxeMVaGu5L05ZMtEAAAAASUVORK5CYII="
}
